export const login = 'uit/checklogin'
export const newlogin = 'uit/newlogin'
export const deadline = 'uit/deadline'
export const eschedule = 'uit/eschedule'
export const schedule = 'uit/schedule'

export const daaCroom = 'uit/croom'
export const compensatory = 'uit/compensatory'
export const comment = 'uit/comment'
export const rescomment = 'uit/rescomment'
export const chatreal = 'uit/chatreal'

export const creategroup = 'uit/creategroup'
export const getdatacg = 'uit/getcreategroup'
export const getlistuser = 'uit/listuser'
export const getlistGroup = 'uit/grouploading'
export const getdataGroup = 'uit/getdataGroup'
export const getspecialdataGroup = 'uit/getspecialdataGroup'
export const chatting = 'http://127.0.0.1:3000'