//user
export const SAVE_ACCOUNT = 'SAVE_ACCOUNT'
//deadline
export const SAVE_DEADLINE = 'SAVE_DEADLINE'
//Eschedule
export const SAVE_ESCHEDULE = 'SAVE_ESCHEDULE'
//Schedule
export const SAVE_SCHEDULE = 'SAVE_SCHEDULE'

export const SELECT_DATE = 'SELECT_DATE'

//SAVE_DAA_CROOM
export const SAVE_DAA_CROOM = 'SAVE_DAA_CROOM'
//SAVE_COMPENSATORY

export const SAVE_COMPENSATORY = 'SAVE_COMPENSATORY'

//SAVE_COMMENT
export const SAVE_COMMENT = 'SAVE_COMMENT'
//vSELECT_RESCOMMENT

export const SAVE_RESCOMMENT = 'SELECT_RESCOMMENT'

//SAVE_CHATREAL
export const SAVE_CHATREAL = 'SAVE_CHATREAL'

export const SAVE_CREATEGROUP = 'SAVE_CREATEGROUP'
